### ISSUE TITLE
Add required disk space to requirements in README

### ISSUE THREAD

**Issue by raginggoblin** [WeAreFairphone/android_device_fairphone_FP3#18]
My build stopped with the following message:
'/root/build.sh: line 151: cannot create temp file for here-document: No space left on device'

Apparently the build needs more than 65 GB on disk. Docker volume of build system took all space left. It would be convenient if the README pointed out the required disk space.

**Comment by klic** [comment]
I had to give the lineage directory nearly 200G....

**Comment by raginggoblin** [comment]
> I had to give the lineage directory nearly 200G....

Wow, in that case I have to repartition my disk. I did not use LVM :sob:

**Comment by klic** [comment]
I switched to using LVM long ago. Just way more flexible, e.g. creating throw away file systems,, intermediate storage for backups....

**Comment by theraser** [comment]
The required disk space (currently 100GB) is already mentioned at the linked build guide (https://wiki.lineageos.org/devices/river/build). But since this isn't enough anymore, there is a pull request regarding this old (?) information: https://github.com/LineageOS/lineage_wiki/pull/145

**Comment by mstaz** [comment]
Unfortunately building Android requires a lot of disk space. I think you can save a little space by adding `--depth=1` to the `repo init` command.

**Comment by dk1978** [comment]
README now mentions the needed space.
