### ISSUE TITLE
Gapps install tutorial

### ISSUE THREAD

**Issue by gazben** [WeAreFairphone/android_device_fairphone_FP3#19]
Hi,

There are multiple bits and pieces, on how to install gapps, but there is no "official" guide.
Example thread: https://forum.fairphone.com/t/rom-unofficial-lineageos-16-0-for-fp3/59849/127

Did somebody succeed in installing Gapps to this ROM? 
If so, can you make a step by step guide on, how to do it?

**Comment by mstaz** [comment]
In the LOS [requirements](https://github.com/LineageOS/charter/blob/master/device-support-requirements.md#verity) I fell over this:
All devices MUST disable verity on the system image for userdebug builds.

So maybe we need to disable AVB for it somehow. But that's just an idea. As disabling verity also doesn't work, it may also be caused by something else.

**Comment by klic** [comment]
I did it, and this has been tested by (at least) one other person

    boot twrp from fastboot
    install LOS
    boot twrp via fastboot (this switches slots)
    install Magisk
    boot twrp via fastboot
    install OpenGapps (arm64)

**Comment by Thulium-Drake** [comment]
My 2c

I was able to install my phone with LOS and GApps Pico after a lot of trial and error. This is what my notes boiled down to:
# Installation
* Unlock bootloader
 https://www.fairphone.com/en/bootloader-unlocking-code-for-fairphone-3/
* Download TWRP, LineageOS (without MicroG!), Magisk and OpenGApps
 https://eu.dl.twrp.me/FP3/twrp-3.4.0-0-FP3.img.html
 https://github.com/WeAreFairphone/android_device_fairphone_FP3/releases
 https://opengapps.org/
 https://github.com/topjohnwu/Magisk/releases
* Boot TWRP from fastboot
 fastboot boot bootloader
 fastboot boot twrp-3.4.0-0-FP3.img
* Backup existing firmware
  * First wipe data: Wipe -> Format Data
  * Set backup job: Backup -> Check all
  * Copy files to PC
 adb pull /data/media/0/TWRP/BACKUPS
* Install LineageOS image
  * Advanced -> ADB Sideload
 adb sideload lineage-16.0-20200819-UNOFFICIAL-FP3.zip
* Reboot and check if the recovery is working, you will _not_ see TWRP, but Lineage Recovery
 adb reboot recovery
* Reboot again to TWRP
 adb reboot bootloader
 fastboot boot twrp-3.4.0-0-FP3.img
* Flash OpenGApps and Magisk
 * Advanced -> ADB Sideload
 adb sideload open_gapps-arm64-9.0-pico-20200820.zip
 adb sideload Magisk-v20.4.zip
* Reboot the phone, enjoy!

# Issues
* Device is corrupted notification: you can try resetting the bootloader with
 adb reboot "dm-verity enforcing"
* I had to disable and enable dm-verity to make the Play Store 'stick' (it was disappearing after I flashed it)
 adb reboot bootloader
 fastboot boot twrp-3.4.0-0-FP3.img
 adb disable-verity
 adb reboot
  * Wait for the device to reboot, check Play Store and repeat to enable verity again.

# Fallback
If all else fails, this article tells you how to completely factory restore it: https://support.fairphone.com/hc/en-us/articles/360043337512

**Comment by gazben** [comment]
@Thulium-Drake This is it. It works. Can you make a pull request to add it to the readme?

**Comment by Thulium-Drake** [comment]
oh, sorry, missed that... thanks for making the PR on my behalf!
