### ISSUE TITLE
WiFi hotspot not working

### ISSUE THREAD

**Issue by iexos** [WeAreFairphone/android_device_fairphone_FP3#21]
I cannot find any WiFi with other devices when enabling the WiFi hotspot, it just doesn't appear. Using [this release](https://github.com/WeAreFairphone/android_device_fairphone_FP3/releases/tag/20200626-unofficial)

**Comment by danyright** [comment]
I had the same issue - Wifi hotspot was shown as active, but it wasn't working (unable to see the network from other devices).
I switched to /e/'s build and it does work with it.

**Comment by dk1978** [comment]
This turned out to be a kernel issue, already noticed and fixed by the /e/ guys. 
Fixed in our kernel tree by merge now.
