### ISSUE TITLE
Mounting /system in twrp does not work

### ISSUE THREAD

**Issue by klic** [WeAreFairphone/android_device_fairphone_FP3#22]
I'm trying to install apps in zip format from twrp. This fails with unable to (un)mount system . Also,  mounting from within twrp seems to not mount system as expected. 
I don't know where this is a rom problem or twrp, but on FPOS this works. 

(I built the rom myself, if this makes a difference)

**Comment by dk1978** [comment]
I would try to contact the TWRP for Fairphone author k4y0z here:
[https://forum.fairphone.com/t/twrp-for-fairphone-3/56995](https://forum.fairphone.com/t/twrp-for-fairphone-3/56995)

**Comment by klic** [comment]
Thanks, it looks like the installation fails for different reasons
