### ISSUE TITLE
Release cycle?

### ISSUE THREAD

**Issue by Thulium-Drake** [WeAreFairphone/android_device_fairphone_FP3#27]
Hi guys,

Amazing work so far! I've got my FP3 up and running, and I ran into some things I have some questions about.

First of all, what is the release cycle for this build? Are you following LOS' cycle or is it with a different frequency?

Related, what is the current status of official LOS support? I thought I read somewhere you are working to get this build adopted by the project.

**Comment by theraser** [comment]
I just noticed that die Fairphone 3 is already available here: https://download.lineageos.org/FP3

Now I'm not sure how the two Github repos (https://github.com/WeAreFairphone/android_device_fairphone_FP3 and https://github.com/LineageOS/android_device_fairphone_FP3) compare and if the new one already resolves this issue here.

**Comment by dk1978** [comment]
Yes, I think we ought to retire the unofficial repositories for now. I will not work here any more. @mstaz ?

To answer your question: the official device tree [https://github.com/LineageOS/android_device_fairphone_FP3](https://github.com/LineageOS/android_device_fairphone_FP3) is a heavily modified and rebased version that resulted after review.

**Comment by Thulium-Drake** [comment]
> Yes, I think we ought to retire the unofficial repositories for now. I will not work here any more. @mstaz ?
> 
That'd be a good idea, maybe also migrate/copy the open issues to the new repo so they can be investigated there if they still apply.
> To answer your question: the official device tree https://github.com/LineageOS/android_device_fairphone_FP3 is a heavily modified and rebased version that resulted after review.

**Comment by mstaz** [comment]
Yes, I'd also say it makes sense to move everything to official LOS repos.

**Comment by Thulium-Drake** [comment]
There is an official release now, so this is no longer applicable
