### ISSUE TITLE
Bootloop before the new update

### ISSUE THREAD

**Issue by RichardBeaudelaire** [WeAreFairphone/android_device_fairphone_FP3#35]
Hi everyone,

I've installed lineageos on m'y fairphone 3 few weeks ago and i'm very happy till now.
A new udpate appears today and saddly leads me to a boot loop. I had to factory reset thé phone to ends this loop and obviously I lost all my data.
My mistake was to not make a backup before update lineage but as the 2 last updates were successful and smooth I was confident.
The weird thing is that before the factory reset, phone finally boot and the new update seems correctly installed on the phone (exept all my data has been wiped !)
An idea of what kind of mistake I could made on that udpate?

Cheers

**Comment by dk1978** [comment]
Hi Richard,
Note that this is the unofficial LineageOS project, it will probably be retired soon since we have official [LineageOS support for FP3](https://wiki.lineageos.org/devices/FP3). Which version of LineageOS were you using before? Unofficial/Official? 16.0 or the new 17.1 alpha?

**Comment by RichardBeaudelaire** [comment]
Oh I didn't realized I was the unofficial project! 
I already was on the official version, was on 16.0 official and updated it to official 16.0 with the official udpate manager.

**Comment by dk1978** [comment]
It will be hard to understand what went wrong after a factory reset. I am sorry you lost your data. If you like, continue this conversation by private message to me in the Fairphone forum, I am @dk1978 there was well.
